# Generated by Django 4.2.17 on 2024-12-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(default='India', max_length=200,null=False),
            preserve_default=True,
        ),
    ]
